
package Vistas;


import Clases.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class registro_productos1 extends javax.swing.JFrame {
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    Conexion conn = new Conexion();
    Connection con = conn.getConexion();
    
        public void Conectar() {
            btn_guardar.setVisible(false);
            btn_buscar.setVisible(false);
        try {
            st = con.createStatement();
            rs = st.executeQuery("Select * from PRODUCTO;");
            rs.next();
            llenarDatos();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error 000" + err.getMessage());
        }

    }

    public void llenarDatos() {
        try {
                this.jtf_id.setText(rs.getString("PRODUCTOID"));
                this.jtf_clave.setText(rs.getString("CLAVE"));
                this.jtf_nombre.setText(rs.getString("NOMBREP"));
                this.jtf_contenido.setText(rs.getString("CONTENIDO"));
                this.cbx_unidades.setSelectedItem(rs.getString("UNIDADES"));
                this.jtf_venta.setText(rs.getString("PRECIOVENTA"));
                this.jtf_stok.setText(rs.getString("STOKACTUAL"));
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
    
    
    
    private void limpiarCajas(){
     
     jtf_clave.setText(null);
     jtf_nombre.setText(null);
     jtf_contenido.setText(null);
     cbx_unidades.setSelectedIndex(0);
     jtf_venta.setText(null);
     jtf_stok.setText(null);
     
     
 }
    public registro_productos1() {
        initComponents();
        jtf_id.setVisible(false);
        Conectar();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_clave = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_contenido = new javax.swing.JTextField();
        cbx_unidades = new javax.swing.JComboBox<>();
        jtf_venta = new javax.swing.JTextField();
        jtf_stok = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_guardar = new javax.swing.JButton();
        jbt_modificar = new javax.swing.JButton();
        jtb_eliminar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        jtf_id = new javax.swing.JTextField();
        jp_movimiento = new javax.swing.JPanel();
        btn_primero = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        btn_ultimo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 153));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Registro de Productos");
        jLabel6.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Clave:");

        jLabel2.setBackground(new java.awt.Color(0, 51, 204));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Nombre:");

        jLabel3.setBackground(new java.awt.Color(0, 51, 204));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Contenido:");

        jLabel4.setBackground(new java.awt.Color(0, 51, 204));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Unidades:");

        jLabel5.setBackground(new java.awt.Color(0, 51, 204));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Precio venta:");

        jLabel7.setBackground(new java.awt.Color(0, 51, 204));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Stok Actual:");

        jtf_clave.setBackground(new java.awt.Color(255, 255, 153));
        jtf_clave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtf_clave.setForeground(new java.awt.Color(0, 0, 153));

        jtf_nombre.setBackground(new java.awt.Color(255, 255, 153));
        jtf_nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtf_nombre.setForeground(new java.awt.Color(0, 0, 153));

        jtf_contenido.setBackground(new java.awt.Color(255, 255, 153));
        jtf_contenido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtf_contenido.setForeground(new java.awt.Color(0, 0, 153));

        cbx_unidades.setBackground(new java.awt.Color(255, 255, 153));
        cbx_unidades.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbx_unidades.setForeground(new java.awt.Color(0, 0, 153));
        cbx_unidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "kg", "g", "l", "ml", "m", "cm" }));

        jtf_venta.setBackground(new java.awt.Color(255, 255, 153));
        jtf_venta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtf_venta.setForeground(new java.awt.Color(0, 0, 153));

        jtf_stok.setBackground(new java.awt.Color(255, 255, 153));
        jtf_stok.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtf_stok.setForeground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btn_guardar.setBackground(new java.awt.Color(255, 255, 153));
        btn_guardar.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(0, 0, 204));
        btn_guardar.setText("Guardar");
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jbt_modificar.setBackground(new java.awt.Color(255, 255, 153));
        jbt_modificar.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jbt_modificar.setForeground(new java.awt.Color(0, 0, 204));
        jbt_modificar.setText("Modificar");
        jbt_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_modificarMouseClicked(evt);
            }
        });

        jtb_eliminar.setBackground(new java.awt.Color(255, 255, 153));
        jtb_eliminar.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jtb_eliminar.setForeground(new java.awt.Color(0, 0, 204));
        jtb_eliminar.setText("Eliminar");
        jtb_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_eliminarMouseClicked(evt);
            }
        });

        btn_nuevo.setBackground(new java.awt.Color(255, 255, 153));
        btn_nuevo.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(0, 0, 204));
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nuevoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtb_eliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(jbt_modificar)
                    .addComponent(jtb_eliminar)
                    .addComponent(btn_nuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_buscar.setBackground(new java.awt.Color(255, 255, 153));
        btn_buscar.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(0, 0, 204));
        btn_buscar.setText("Buscar");
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });

        jtf_id.setEditable(false);

        jp_movimiento.setBackground(new java.awt.Color(255, 255, 255));

        btn_primero.setBackground(new java.awt.Color(255, 255, 153));
        btn_primero.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btn_primero.setForeground(new java.awt.Color(0, 0, 204));
        btn_primero.setText("|<");
        btn_primero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_primeroMouseClicked(evt);
            }
        });

        btn_atras.setBackground(new java.awt.Color(255, 255, 153));
        btn_atras.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btn_atras.setForeground(new java.awt.Color(0, 0, 204));
        btn_atras.setText("<<");
        btn_atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_atrasMouseClicked(evt);
            }
        });

        btn_siguiente.setBackground(new java.awt.Color(255, 255, 153));
        btn_siguiente.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btn_siguiente.setForeground(new java.awt.Color(0, 0, 204));
        btn_siguiente.setText(">>");
        btn_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_siguienteMouseClicked(evt);
            }
        });

        btn_ultimo.setBackground(new java.awt.Color(255, 255, 153));
        btn_ultimo.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btn_ultimo.setForeground(new java.awt.Color(0, 0, 204));
        btn_ultimo.setText(">|");
        btn_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ultimoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_movimientoLayout = new javax.swing.GroupLayout(jp_movimiento);
        jp_movimiento.setLayout(jp_movimientoLayout);
        jp_movimientoLayout.setHorizontalGroup(
            jp_movimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_movimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_primero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_siguiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ultimo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_movimientoLayout.setVerticalGroup(
            jp_movimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_movimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_movimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_primero)
                    .addComponent(btn_atras)
                    .addComponent(btn_siguiente)
                    .addComponent(btn_ultimo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_clave, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(jtf_contenido)
                                    .addComponent(jtf_venta)
                                    .addComponent(jtf_stok))
                                .addGap(18, 18, 18)
                                .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_buscar))
                            .addComponent(jtf_nombre)
                            .addComponent(cbx_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp_movimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbx_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jtf_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jp_movimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 153));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 204));

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        
        
        try{
            
            ps = con.prepareStatement("INSERT INTO producto (CLAVE, NOMBREP, CONTENIDO, UNIDADES, PRECIOVENTA, STOKACTUAL) VALUES(?,?,?,?,?,?) ");
            ps.setString(1, jtf_clave.getText());
            ps.setString(2, jtf_nombre.getText());
            ps.setString(3, jtf_contenido.getText());
            ps.setString(4, cbx_unidades.getSelectedItem().toString());
            ps.setString(5, jtf_venta.getText());
            ps.setString(6, jtf_stok.getText());
            
            
            int res = ps.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Registro Guardado");
               
  
            } else {
                 JOptionPane.showMessageDialog(null, "Error al Guardar");
                 
            }
            
            
            
            
        } catch(Exception e){
            System.err.println(e);
        }
     
                 
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        jtb_eliminar.setVisible(true);
        btn_guardar.setVisible(false);
        try{
            
          
            ps = con.prepareStatement("SELECT * FROM producto WHERE CLAVE = ?");
            ps.setString(1, jtf_clave.getText());
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                jtf_id.setText(rs.getString("PRODUCTOID"));
                jtf_nombre.setText(rs.getString("NOMBREP"));
                jtf_contenido.setText(rs.getString("CONTENIDO"));
                cbx_unidades.setSelectedItem(rs.getString("UNIDADES"));
                jtf_venta.setText(rs.getString("PRECIOVENTA"));
                jtf_stok.setText(rs.getString("STOKACTUAL"));
                
            } else {
                JOptionPane.showMessageDialog(null, "No existe producto con esta clave");
            }
            
        } catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void jbt_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_modificarMouseClicked
        
        try{
            
          
            ps = con.prepareStatement("UPDATE producto SET CLAVE=?, NOMBREP=?, CONTENIDO=?, UNIDADES=?, PRECIOVENTA=?, STOKACTUAl=? WHERE PRODUCTOID=?");
            ps.setString(1, jtf_clave.getText());
            ps.setString(2, jtf_nombre.getText());
            ps.setString(3, jtf_contenido.getText());
            ps.setString(4, cbx_unidades.getSelectedItem().toString());
            ps.setString(5, jtf_venta.getText());
            ps.setString(6, jtf_stok.getText());
            ps.setString(7, jtf_id.getText());
            
            int res = ps.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Producto Modificado");
                
               
            } else {
                 JOptionPane.showMessageDialog(null, "Error al Modificar ");
                 
            }
                    
            
           
            
        } catch(Exception e){
            System.err.println(e);
        }
        
    }//GEN-LAST:event_jbt_modificarMouseClicked

    private void jtb_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_eliminarMouseClicked
     
        try{
            
            
            ps = con.prepareStatement("DELETE FROM producto WHERE PRODUCTOID=?");
            ps.setInt(1, Integer.parseInt(jtf_id.getText()));
            
            int res = ps.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                
            } else {
                 JOptionPane.showMessageDialog(null, "Error al eliminar ");
                 
            }
            
            
            
            
        } catch(Exception e){
            System.err.println(e);
        }
        
    }//GEN-LAST:event_jtb_eliminarMouseClicked

    private void btn_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoMouseClicked
        btn_guardar.setVisible(true);
        btn_buscar.setVisible(true);
        jtb_eliminar.setVisible(false);
        limpiarCajas();
        
    }//GEN-LAST:event_btn_nuevoMouseClicked

    private void btn_primeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_primeroMouseClicked
        btn_guardar.setVisible(false); 
         jtb_eliminar.setVisible(true);
        try {
            rs.first();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 004" + ex.getMessage());
        }
    
    }//GEN-LAST:event_btn_primeroMouseClicked

    private void btn_atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atrasMouseClicked
       btn_guardar.setVisible(false);
       jtb_eliminar.setVisible(true);
        try {
            if (!rs.isFirst()) {
                rs.previous();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 003" + ex.getMessage());
        }
    }//GEN-LAST:event_btn_atrasMouseClicked

    private void btn_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siguienteMouseClicked
       btn_guardar.setVisible(false);
       jtb_eliminar.setVisible(true);
        try {
            if (!rs.isLast()) {
                rs.next();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 002" + ex.getMessage());
        }
    }//GEN-LAST:event_btn_siguienteMouseClicked

    private void btn_ultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ultimoMouseClicked
        btn_guardar.setVisible(false);
        jtb_eliminar.setVisible(true);
        try {
            rs.last();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 005" + ex.getMessage());
        }
    }//GEN-LAST:event_btn_ultimoMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
                 Inicio entra=new Inicio();
                 entra.setVisible(true);
                 this.dispose(); 
    }//GEN-LAST:event_jMenu1MouseClicked

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_productos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_productos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_productos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_productos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_productos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_primero;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JButton btn_ultimo;
    private javax.swing.JComboBox<String> cbx_unidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbt_modificar;
    private javax.swing.JPanel jp_movimiento;
    private javax.swing.JButton jtb_eliminar;
    private javax.swing.JTextField jtf_clave;
    private javax.swing.JTextField jtf_contenido;
    private javax.swing.JTextField jtf_id;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_stok;
    private javax.swing.JTextField jtf_venta;
    // End of variables declaration//GEN-END:variables
}
