drop database SistemaTienda;
create database SistemaTienda;
use SistemaTienda;



CREATE TABLE TIPO_USUARIOS(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRET VARCHAR(80) NOT NULL);


INSERT INTO TIPO_USUARIOS( NOMBRET) VALUES
('Administrador'),
('Invitado');

CREATE TABLE USUARIOS(
USUARIOSID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
USUARIO VARCHAR(45) NOT NULL,
PASSWORD VARCHAR(45) NOT NULL,
NOMBREU VARCHAR(80) NOT NULL,
CORREO VARCHAR(45) NOT NULL,
LAST_SESSION TIMESTAMP NULL,
ID_TIPO INT  NULL,
FOREIGN KEY (ID_TIPO) REFERENCES TIPO_USUARIOS (ID));



CREATE TABLE PRODUCTO(
PRODUCTOID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CLAVE VARCHAR(20) NOT NULL,
NOMBREP VARCHAR(45) NOT NULL,
CONTENIDO INT(20) NOT NULL,
UNIDADES VARCHAR(45) NOT NULL,
PRECIOVENTA INT(20) NOT NULL,
STOKACTUAL INT (20) NOT NULL);

INSERT INTO PRODUCTO(CLAVE,NOMBREP,CONTENIDO,UNIDADES,PRECIOVENTA,STOKACTUAL)VALUE
('001','cocacola',600,'ml',21,5),
('002','galletas emperador',5,'g',21,5),
('003','cocacola1',100,'g',21,5);



 CREATE TABLE DISTRIBUIDOR(
 DISTRIBUIDORID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 CLAVE VARCHAR(20) NOT NULL,
 NOMBRED VARCHAR(20) NOT NULL,
 TELEFONO CHAR(15) NOT NULL,
 DIRECCION VARCHAR(50) NOT NULL,
 ESTADO VARCHAR(20) NOT NULL,
 CIUDAD VARCHAR(20) NOT NULL);

INSERT INTO DISTRIBUIDOR (CLAVE,NOMBRED, TELEFONO, DIRECCION, ESTADO, CIUDAD) VALUES
('001','GAMESA',017725824926,'AQUILES SERDAN 1514 CAMINO INTERPARCELARIA','AGUASCALIENTES','AGUASCALIENTES'),
('002','BIMBO',017757530826,'MIGUEL HIDALGO 315, JAVIER ROJO GÓMEZ','HIDALGO','TULANCINGO'),
('003','MARINELA',0447735121823,'AV SAN PABLO XALPA 2, SANTA BARBARA','CIUDAD DE MEXICO','CDMX'),
('004','TOTIS',017797969220,'CALLE 4 SUR No.123, Cd. INDUSTRIAL TIZAYUCA, 43800','HIDALGO','TIZAYUCA');



CREATE TABLE COMPRA(
 IDCOMPRA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 FECHA DATE NOT NULL,
 CANTIDAD INT NOT NULL,
 PRECIO INT NOT NULL,
 TOTAL FLOAT NOT NULL,
 PRODUCTOID INT  NULL,
 DISTRIBUIDORID INT  NULL,
 FOREIGN KEY (PRODUCTOID) REFERENCES PRODUCTO(PRODUCTOID),
 FOREIGN KEY (DISTRIBUIDORID) REFERENCES DISTRIBUIDOR(DISTRIBUIDORID));
 
 CREATE TABLE VENTA(
 IDVENTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 FECHA DATE NOT NULL,
 CANTIDAD INT NOT NULL,
 PRECIO INT NOT NULL,
 TOTAL FLOAT NOT NULL,
 PRODUCTOID INT  NULL,
 USUARIOSID INT  NULL,
 FOREIGN KEY (PRODUCTOID) REFERENCES PRODUCTO(PRODUCTOID),
 FOREIGN KEY (USUARIOSID) REFERENCES USUARIOS(USUARIOSID));
 
 
SELECT  USUARIOSID,USUARIO,PASSWORD,NOMBREU,CORREO,LAST_SESSION,NOMBRET
FROM USUARIOS
INNER JOIN TIPO_USUARIOS ON USUARIOS.ID_TIPO=TIPO_USUARIOS.ID;







